# Generated by Django 2.2.12 on 2022-01-05 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220105_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regions',
            old_name='hospitalID',
            new_name='hospital',
        ),
        migrations.RemoveField(
            model_name='hospitals',
            name='cityID',
        ),
        migrations.AddField(
            model_name='hospitals',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Cities'),
        ),
    ]
